Add Postgress 13 job
Named postgres, from now on only packages and store directory will be
named per version. The reason why previous job contained version is that
previous bosh create-env did not drain/stop the jobs properly on update
and that resulted in unclean state of the postgres data. So postgres-10
had to restart postgres-9 job and get into clean state. bosh create-env
now properly drains the jobs so postgres should shut down cleanly.

Mounting postgres-10 and postgres-13 data directories in BPM to run
pg_upgrade.  Removed persistent_disk option from bpm config cause it
creates /var/vcap/store/postgres which we are not using anymore.

bosh-deployment is not updated yet with the switch to postgres job
because bbr release does not yet support postgres 13.
https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release

[#176811018](https://www.pivotaltracker.com/story/show/176811018)

diff --git a/jobs/postgres-10/templates/pre-start.erb b/jobs/postgres-10/templates/pre-start.erb
--- a/jobs/postgres-10/templates/pre-start.erb
+++ b/jobs/postgres-10/templates/pre-start.erb
@@ -14,6 +14,11 @@ USER='<%= p("postgres.user") %>'
 
 sysctl -w "kernel.shmmax=67108864"
 
+if [[ -d /var/vcap/store/postgres-13 ]]; then
+  echo "Intentionally failing because data from a newer postgres job may already exist in /var/vcap/store/postgres-13"
+  exit 1
+fi
+
 if [[ -d /var/vcap/store/postgres ]]; then
   echo "Please use a previous bosh release version (264.x or lower) to migrate data from postgres to postgres-9.4."
   exit 1
@@ -74,6 +79,7 @@ if [[ -f /var/vcap/store/postgres-10/fresh ]] ; then
       --new-datadir=$DATA_DIR"
 
     echo "successfully upgraded from postgres-9.4"
+    rm -rf '/var/vcap/store/postgres-9'
   fi
 
   rm /var/vcap/store/postgres-10/fresh
